//! Phase R.4 — PDF Rendering Port.
//!
//! `tera` port of `templates/quote_pdf_template.html`, replacing `server/pdf_render.js`'s
//! nunjucks-based render step. `server/pdf_render.js` / `server/ipc_handlers.js` are the
//! reference and are NOT modified.
//!
//! ## Field-by-field diff against the real `quote_pdf_template.html` (done before
//! writing `PdfContext`, per the brief's Section 1 instruction)
//! Template variables referenced: customer_name, offer_reference, po_box, quote_date,
//! location, contact_person, sales_person, equipment_category, rate_basis, line_items
//! (item_order, item_description, equipment_spec, make_model, quantity, unit_rate),
//! subtotal, vat_amount, grand_total, terms_line_1..9, rate_basis_legend_html,
//! authorized_signatory. `page_count` is part of `generate_quote_pdf`'s JS data
//! contract but is NOT referenced anywhere in the template body itself (grep of the
//! attached `quote_pdf_template.html` confirms no `{{ page_count }}` — the real page
//! count comes from `@page { @bottom-center: counter(page) }` in the CSS, not this
//! variable). Kept as a struct field anyway so `PdfContext` stays a superset of the JS
//! contract (silently dropping a contract field felt riskier than carrying one unused
//! field) — flagged here rather than silently omitted or silently assumed used.

use serde::Serialize;
use tera::{Tera, Context, Value, to_value};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize)]
pub struct LineItemContext {
    pub item_order: i64,
    pub item_description: String,
    pub equipment_spec: Option<String>,
    pub make_model: String,
    pub quantity: i64,
    pub unit_rate: f64,
    /// Per-item rate basis (Daily/Weekly/Monthly) — the table used to show a single
    /// quote-level `rate_basis` string in the column header regardless of what basis
    /// each individual item actually used, which is misleading once items can have
    /// different bases (the frontend line-item form allows setting this per item).
    /// Shown per-row now instead.
    pub rate_basis: String,
    /// `unit_rate * quantity` — previously absent entirely, so the table never showed
    /// the extended amount for a line (e.g. "10 x 50.00" never resolved to "500.00"
    /// anywhere in the document). Computed once here so the template only ever prints
    /// it, never recomputes it.
    pub line_total: f64,
}

#[derive(Debug, Clone, Serialize)]
pub struct PdfContext {
    pub customer_name: String,
    pub offer_reference: String,
    pub po_box: String,
    pub quote_date: String,
    pub location: String,
    /// Not referenced in the template body (see module doc) — carried for JS-contract
    /// parity only.
    pub page_count: String,
    pub contact_person: String,
    pub sales_person: String,
    pub equipment_category: String,
    pub rate_basis: String,
    pub line_items: Vec<LineItemContext>,
    pub subtotal: f64,
    pub vat_amount: f64,
    pub grand_total: f64,
    /// Phase 4.2: replaces the previous 9 fixed `terms_line_1..9` fields. Those forced
    /// the template's `<ol>` to always render exactly 9 `<li>` items regardless of how
    /// much real content existed — an empty `terms_conditions` quote still produced 9
    /// empty numbered bullets in the PDF (visible in the sample PDF this phase started
    /// from). A `Vec` + `{% for %}` loop (template updated alongside this struct)
    /// renders exactly as many list items as there are real compliance terms, and none
    /// when there are none.
    pub terms: Vec<String>,
    /// Phase 4.2: previously the template hardcoded the literal string "VAT (5%, AED)"
    /// regardless of what `vat_amount` was actually calculated from — misleading once a
    /// quote can select a tax_rule with a different rate/region (Phase 4.1). Built by
    /// the caller (`build_pdf_context`) from whichever `tax_rules` row was actually
    /// resolved, e.g. "VAT (UAE Standard VAT 5%, AED)", falling back to a generic label
    /// when no library rule was selected (pre-Phase-4 quotes).
    pub vat_label: String,
    /// Generated by the ported RateBasisLegend logic upstream (Rust equivalent not in
    /// R.4's scope — R.4 only receives and injects the string, same as the template
    /// does via `{{ rate_basis_legend_html | safe }}`). Whatever produces this on the
    /// Rust side must escape/produce trusted HTML itself, exactly as
    /// `getRateBasisLegendHTML()` does today — `safe` here means "already sanitized by
    /// the producer," not "sanitized by this filter."
    pub rate_basis_legend_html: String,
    pub authorized_signatory: String,
}

/// format_currency filter — Decision 3a (Worker's stated convention, flagged for
/// Architect confirmation like every other R-phase decision):
///
/// Ported to match `server/pdf_render.js`'s existing filter EXACTLY:
///   `Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })`
/// i.e. US-locale comma thousands separators, always exactly 2 decimal places, NO
/// currency symbol or "AED" text baked into the filter output — the template's own
/// static text ("Subtotal (AED)", "{{ rate_basis }} Rate (AED)") supplies the currency
/// label, matching route-map-v2.docx's AED-only scope. This filter does not attempt
/// multi-currency support, matching that scope decision.
///
/// Non-numeric / missing input is treated as 0.0, matching the JS reference's
/// `Number(value) || 0` fallback (`Number(undefined)` is `NaN`, and `NaN || 0` is `0`).
fn format_currency_filter(value: &Value, _args: &HashMap<String, Value>) -> tera::Result<Value> {
    let num: f64 = match value {
        Value::Number(n) => n.as_f64().unwrap_or(0.0),
        Value::String(s) => s.parse::<f64>().unwrap_or(0.0),
        _ => 0.0,
    };
    let formatted = format_with_us_thousands(num);
    to_value(formatted).map_err(|e| tera::Error::msg(e.to_string()))
}

/// Manual US-locale thousands-separator + fixed-2-decimal formatter. Written by hand
/// rather than pulled from a crate: this is the entire scope of what
/// `toLocaleString('en-US', {min:2, max:2})` needs to reproduce for AED-only amounts
/// (no negative-amount or scientific-notation cases exist anywhere in the reference
/// data), and pulling in a locale-formatting crate for one function felt like more risk
/// (another crate to verify against `Cargo.toml`'s existing, already-justified list)
/// than it was worth. Verified by unit test below against concrete before/after pairs,
/// not just eyeballed.
fn format_with_us_thousands(num: f64) -> String {
    let negative = num < 0.0;
    let num = num.abs();
    // Round to 2 decimals first so the integer/fraction split below is exact, avoiding
    // float-formatting edge cases (e.g. 1234.005 rounding surprises).
    let cents = (num * 100.0).round() as i64;
    let int_part = cents / 100;
    let frac_part = cents % 100;

    let int_str = int_part.to_string();
    let mut grouped = String::new();
    for (i, c) in int_str.chars().rev().enumerate() {
        if i != 0 && i % 3 == 0 {
            grouped.push(',');
        }
        grouped.push(c);
    }
    let grouped: String = grouped.chars().rev().collect();

    let sign = if negative { "-" } else { "" };
    format!("{}{}.{:02}", sign, grouped, frac_part)
}

/// Builds the Tera engine with the ported template and filter registered.
/// `template_source` is passed in (rather than loaded via `FileSystemLoader`, which
/// `server/pdf_render.js` uses) so this function is testable without depending on a
/// real filesystem layout — the real app wiring (R.5) would load
/// `include_str!("../../templates/quote_pdf_template.html")` and pass it here.
pub fn build_engine(template_source: &str) -> tera::Result<Tera> {
    let mut tera = Tera::default();
    tera.add_raw_template("quote_pdf_template.html", template_source)?;
    tera.register_filter("format_currency", format_currency_filter);
    // Template calls `{% for %}`/`{{ }}`/`{% if %}`/`| safe` — all core Tera syntax
    // (verified by successfully compiling the real, attached template source below in
    // tests, not assumed from surface similarity to Jinja2/nunjucks).
    Ok(tera)
}

pub fn render_quote_pdf_html(template_source: &str, context: &PdfContext) -> tera::Result<String> {
    let tera = build_engine(template_source)?;
    let ctx = Context::from_serialize(context)?;
    tera.render("quote_pdf_template.html", &ctx)
}

#[cfg(test)]
mod tests {
    use super::*;

    const REAL_TEMPLATE: &str = include_str!("../../templates/quote_pdf_template.html");

    fn sample_context() -> PdfContext {
        PdfContext {
            customer_name: "Acme Construction LLC".into(),
            offer_reference: "QN-EH/211/2026".into(),
            po_box: "PO Box 12345".into(),
            quote_date: "2026-09-04".into(),
            location: "Abu Dhabi".into(),
            page_count: "1/1".into(),
            contact_person: "Jane Doe".into(),
            sales_person: "John Smith".into(),
            equipment_category: "Excavators".into(),
            rate_basis: "Monthly".into(),
            line_items: vec![
                LineItemContext {
                    item_order: 1,
                    item_description: "Excavator, 20T".into(),
                    equipment_spec: Some("Cap: 20 tonnes, Model: CAT320".into()),
                    make_model: "Caterpillar 320".into(),
                    quantity: 2,
                    unit_rate: 12345.5,
                    rate_basis: "Monthly".into(),
                    line_total: 24691.0,
                },
                LineItemContext {
                    item_order: 2,
                    item_description: "Generator, 100kVA".into(),
                    equipment_spec: None,
                    make_model: "Cummins".into(),
                    quantity: 1,
                    unit_rate: 300.0,
                    rate_basis: "Weekly".into(),
                    line_total: 300.0,
                },
            ],
            subtotal: 24991.0,
            vat_amount: 1249.55,
            grand_total: 26240.55,
            terms: vec![
                "Rates exclude transportation.".into(),
                "Payment due within 30 days.".into(),
            ],
            vat_label: "VAT (UAE Standard VAT 5%, AED)".into(),
            rate_basis_legend_html: "<div class=\"rate-basis-legend-block\"><h3>Rental Rate Basis</h3></div>".into(),
            authorized_signatory: "Authorized Signatory".into(),
        }
    }

    #[test]
    fn real_template_renders_without_error_and_is_non_empty() {
        let html = render_quote_pdf_html(REAL_TEMPLATE, &sample_context())
            .expect("real quote_pdf_template.html must render under Tera without error");
        assert!(!html.trim().is_empty());
    }

    #[test]
    fn rendered_html_contains_expected_dynamic_values() {
        let html = render_quote_pdf_html(REAL_TEMPLATE, &sample_context()).unwrap();
        assert!(html.contains("Acme Construction LLC"));
        assert!(html.contains("QN-EH&#x2F;211&#x2F;2026"));
        assert!(html.contains("Excavator, 20T"));
        assert!(html.contains("Cap: 20 tonnes, Model: CAT320"));
        assert!(html.contains("Generator, 100kVA"));
        assert!(html.contains("12,345.50"));
        assert!(html.contains("24,991.00"));
        assert!(html.contains("1,249.55"));
        assert!(html.contains("26,240.55"));
        assert!(html.contains("<div class=\"rate-basis-legend-block\">"));
        // Regression coverage for the "line total never shown" gap: each row's
        // extended amount (unit_rate * quantity) must actually appear, and each row's
        // own rate_basis, not a single quote-level header string.
        assert!(html.contains("24,691.00"), "first item's line_total (2 x 12,345.50) must render");
        assert!(html.contains("300.00"), "second item's line_total must render");
        assert!(html.contains("Weekly"), "per-item rate_basis must render for a non-Monthly item");
        assert!(html.contains("Rates exclude transportation."), "selected compliance term text must render");
        assert!(html.contains("Payment due within 30 days."));
        assert!(html.contains("VAT (UAE Standard VAT 5%, AED)"), "dynamic vat_label must render, not a hardcoded '5%' string");
    }

    #[test]
    fn empty_terms_renders_no_list_items_not_nine_empty_bullets() {
        // Regression coverage: the old 9-fixed-field design rendered 9 <li></li> even
        // with zero real terms (visible in the sample PDF Phase 4.2 started from). The
        // Vec-based terms field + {% for %} loop must render exactly zero <li> here.
        let mut ctx = sample_context();
        ctx.terms = vec![];
        let html = render_quote_pdf_html(REAL_TEMPLATE, &ctx).unwrap();
        let li_count = html.matches("<li>").count();
        assert_eq!(li_count, 0, "zero selected terms must produce zero <li> elements");
    }

    #[test]
    fn terms_list_length_matches_number_of_selected_terms() {
        let mut ctx = sample_context();
        ctx.terms = vec!["A".into(), "B".into(), "C".into(), "D".into()];
        let html = render_quote_pdf_html(REAL_TEMPLATE, &ctx).unwrap();
        let li_count = html.matches("<li>").count();
        assert_eq!(li_count, 4, "exactly as many <li> as selected terms, not a fixed 9");
    }

    #[test]
    fn optional_equipment_spec_is_conditionally_omitted() {
        let mut ctx = sample_context();
        ctx.line_items[0].equipment_spec = None;
        ctx.line_items[1].equipment_spec = None;
        let html = render_quote_pdf_html(REAL_TEMPLATE, &ctx).unwrap();
        assert!(!html.contains("item-specs"));
    }

    #[test]
    fn format_currency_matches_js_to_locale_string_convention() {
        assert_eq!(format_with_us_thousands(0.0), "0.00");
        assert_eq!(format_with_us_thousands(5.0), "5.00");
        assert_eq!(format_with_us_thousands(1234.5), "1,234.50");
        assert_eq!(format_with_us_thousands(1234567.891), "1,234,567.89");
        assert_eq!(format_with_us_thousands(999.995), "1,000.00");
        assert_eq!(format_with_us_thousands(-42.1), "-42.10");
    }

    #[test]
    fn format_currency_filter_treats_missing_or_non_numeric_as_zero() {
        let mut args = HashMap::new();
        args.insert("dummy".to_string(), Value::Null);
        let result = format_currency_filter(&Value::Null, &args).unwrap();
        assert_eq!(result, Value::String("0.00".to_string()));

        let result2 = format_currency_filter(&Value::String("not-a-number".into()), &args).unwrap();
        assert_eq!(result2, Value::String("0.00".to_string()));
    }

    #[test]
    fn empty_line_items_renders_without_error() {
        let mut ctx = sample_context();
        ctx.line_items = vec![];
        let html = render_quote_pdf_html(REAL_TEMPLATE, &ctx);
        assert!(html.is_ok());
    }

    #[test]
    fn tera_autoescapes_forward_slash_unlike_nunjucks() {
        let html = render_quote_pdf_html(REAL_TEMPLATE, &sample_context()).unwrap();
        assert!(
            html.contains("QN-EH&#x2F;211&#x2F;2026"),
            "expected Tera's default autoescape to encode '/' as '&#x2F;' — if this \
             fails, Tera's escaping behavior has changed and this finding needs re-checking"
        );
        assert!(
            !html.contains("QN-EH/211/2026"),
            "the raw, unescaped slash should NOT appear verbatim given Tera's default autoescape"
        );
    }
}
